version: "3.8"

services:
  client1:
    build:
      context: .
      dockerfile: Dockerfile
    image: mustakim/network:1.0
    container_name: client1
    networks:
      my_custom_network:
        ipv4_address: 192.168.1.100
    stdin_open: true
    tty: true

  client2:
    build:
      context: .
      dockerfile: Dockerfile
    image: mustakim/network:1.0
    container_name: client2
    networks:
      my_custom_network:
        ipv4_address: 192.168.1.101
    stdin_open: true
    tty: true

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: mustakim/network:1.0
    container_name: server
    networks:
      my_custom_network:
        ipv4_address: 192.168.1.102
    stdin_open: true
    tty: true

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
